# Generated by Django 6.0.4 on 2026-05-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseVH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_codigo', models.CharField(max_length=20, verbose_name='Código Conta')),
                ('conta_descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('av_percentual', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='AV (%)')),
                ('ah_percentual', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='AH (%)')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_vh', to='contabil.periodo', verbose_name='Período')),
                ('periodo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_vh_anterior', to='contabil.periodo', verbose_name='Período Anterior')),
            ],
            options={
                'verbose_name': 'Análise V&H',
                'verbose_name_plural': 'Análises V&H',
                'ordering': ['conta_codigo'],
            },
        ),
        migrations.CreateModel(
            name='DRELinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ordem', models.IntegerField(verbose_name='Ordem')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor (R$)')),
                ('percentual_av', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='AV (%)')),
                ('is_subtotal', models.BooleanField(default=False, verbose_name='É subtotal?')),
                ('is_negativo', models.BooleanField(default=False, verbose_name='Sinal negativo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dre_linhas', to='contabil.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Linha DRE',
                'verbose_name_plural': 'Linhas DRE',
                'ordering': ['periodo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.CharField(choices=[('liquidez', 'Liquidez'), ('rentabilidade', 'Rentabilidade'), ('endividamento', 'Endividamento'), ('atividade', 'Atividade')], max_length=20, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor')),
                ('referencia_setor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Referência Setor')),
                ('status', models.CharField(choices=[('bom', 'Bom'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='bom', max_length=10, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='contabil.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Indicador (KPI)',
                'verbose_name_plural': 'Indicadores (KPIs)',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
