# Generated by Django 6.0.4 on 2026-05-09 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('trim', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=10, verbose_name='Tipo')),
                ('arquivo_origem', models.FileField(blank=True, null=True, upload_to='balancetes/', verbose_name='Arquivo Excel/CSV')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=15, verbose_name='Status')),
                ('log_processamento', models.TextField(blank=True, verbose_name='Log')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('empresa', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('grupo', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PL', 'Patrimônio Líquido'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('CUSTO', 'Custo')], max_length=10, verbose_name='Grupo')),
                ('subgrupo', models.CharField(blank=True, max_length=100, verbose_name='Subgrupo')),
                ('nivel', models.IntegerField(verbose_name='Nível')),
                ('natureza', models.CharField(choices=[('D', 'Devedora'), ('C', 'Credora')], max_length=1, verbose_name='Natureza')),
                ('tipo_conta', models.CharField(choices=[('S', 'Sintética'), ('A', 'Analítica')], max_length=1, verbose_name='Tipo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Anterior')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='contabil.periodo', verbose_name='Período')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabil.planocontas', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Balancete',
                'verbose_name_plural': 'Balancetes',
                'ordering': ['conta__codigo'],
            },
        ),
    ]
