# Generated by Django 6.0.4 on 2026-06-16 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('key', models.CharField(db_index=True, help_text='Token de autenticação gerado automaticamente', max_length=64, unique=True, verbose_name='Chave do Token')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o token está ativo e pode ser usado para fazer requisições', verbose_name='Ativo')),
                ('descricao', models.CharField(blank=True, help_text='Ex: Token para testes do professor, Integração Mobile, etc.', max_length=255, verbose_name='Descrição/Finalidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de API',
                'verbose_name_plural': 'Tokens de API',
            },
        ),
    ]
