# Generated by Django 6.0.4 on 2026-05-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('indicador', models.CharField(choices=[('receita_liquida', 'Receita Líquida'), ('lucro_bruto', 'Lucro Bruto'), ('ebitda', 'EBITDA'), ('lucro_liquido', 'Lucro Líquido'), ('caixa', 'Caixa')], max_length=30, verbose_name='Indicador')),
                ('data_projecao', models.DateField(verbose_name='Data Projetada')),
                ('valor_projetado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Projetado')),
                ('intervalo_inferior', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Intervalo Inferior (80%)')),
                ('intervalo_superior', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Intervalo Superior (80%)')),
                ('meses_projetados', models.IntegerField(default=6, verbose_name='Meses Projetados')),
                ('periodo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes', to='contabil.periodo', verbose_name='Período Base')),
            ],
            options={
                'verbose_name': 'Projeção (Forecast)',
                'verbose_name_plural': 'Projeções (Forecast)',
                'ordering': ['indicador', 'data_projecao'],
            },
        ),
    ]
