# Generated by Django 6.0.4 on 2026-05-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('score_geral', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Geral (0-10)')),
                ('score_liquidez', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Liquidez')),
                ('score_rentabilidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Rentabilidade')),
                ('score_endividamento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Endividamento')),
                ('score_operacional', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Operacional')),
                ('narrativa_ia', models.TextField(blank=True, verbose_name='Narrativa IA (Claude)')),
                ('classificacao', models.CharField(choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('atencao', 'Atenção'), ('risco', 'Risco'), ('critico', 'Crítico')], default='atencao', max_length=15, verbose_name='Classificação')),
                ('modelo_ia_usado', models.CharField(blank=True, default='claude-sonnet-4', max_length=60, verbose_name='Modelo IA')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='contabil.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Score de Risco',
                'verbose_name_plural': 'Scores de Risco',
            },
        ),
    ]
